Models/ErrorViewModel.cs
using System;

namespace SignUpDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SignUpModel.cs
using SignUpDemo.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SignUpDemo.Models
{
    public class SignUpModel
    {
        //public List<string> CityNames { get; set; }

        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "UserName is required")]
        public string UserName { get; set; }
        
        [Required(ErrorMessage = "Password is required")]
        public string Password { get; set; }
        
        [Required(ErrorMessage = "Confirm password is required")]
        [Compare(nameof(Password), ErrorMessage = "Password and confirm password not match")]
        public string ConfirmPassword { get; set; }
        
        [Required(ErrorMessage = "Contact is required")]
        [RegularExpression(@"^([0-9]{10}$)", ErrorMessage = "Invalid Contact Number")]
        
        public string Contact { get; set; }
        [Required(ErrorMessage = "Country Name is required")]
        public string Country { get; set; }
        
        [Required(ErrorMessage = "City name is required")]
        public string City { get; set; }
        
        [Required(ErrorMessage = "Gender is required")]
        public string Gender { get; set; }
        public List<string> CityNames { get; set; }

        [ValidateCheckBox(ErrorMessage = "Terms and Condition is required")]
        public bool Terms { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SignUpDemo.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SignUpDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;
using SignUpDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SignUpDemo.Controllers
{
    public class SignUpController : Controller
    {
        public IActionResult Index()
        {
            return View("AddSignUp", GetModel());
        }
        [NonAction]
        public SignUpModel GetModel()
        {
            List<string> city = new List<string>(){
                "Mumbai",
                "Pune",
                "Delhi",
                "Mysore"
            };
            SignUpModel signUpModel = new SignUpModel()
            { CityNames = city };
            return signUpModel;
        }
        [HttpPost]
        public IActionResult AddSignUp(SignUpModel signUpModel)
        {
            if (ModelState.IsValid)
            {
                ViewBag.ShowMessage = signUpModel.UserName + ", Your Registration done sucessfully !!";
                return View("ViewMessage");
            }
            ViewBag.ShowMessage = signUpModel.UserName + ", Your Registration failed !!";
            return View("ViewMessage");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sign-Up</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-4">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="SignUp" asp-action="Index">SignUpDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SignUpDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/SignUp/AddSignUp.cshtml
@model SignUpDemo.Models.SignUpModel

@{
    ViewData["Title"] = "SignUp";
}

<h1>SignUp</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddSignUp">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label font-weight-bold"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label font-weight-bold"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label font-weight-bold"></label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword" class="control-label font-weight-bold"></label>
                <input asp-for="ConfirmPassword" class="form-control" type="password" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label font-weight-bold" font-weight-bold></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label font-weight-bold"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label font-weight-bold"></label>
                <select asp-for="City" class="custom-select">
                    <option value="">Choose City</option>
                    @foreach (var item in Model.CityNames)
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label font-weight-bold"></label><br />
                Male:&nbsp;<input asp-for="Gender" class="form-check-label" type="radio" value="Male" />
                Female:&nbsp;<input asp-for="Gender" class="form-check-label" type="radio" value="Female" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label font-weight-bold">
                    <input class="form-check-input" asp-for="Terms" /> @Html.DisplayNameFor(model => model.Terms)
                </label>
                <span asp-validation-for="Terms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@*<div>
        <a asp-action="Index">Back to List</a>
    </div>*@

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        jQuery.validator.unobtrusive.adapters.add("checkbox", function (options) {
            if (options.element.tagName.toUpperCase() == "INPUT" && options.element.type.toUpperCase() == "CHECKBOX") {
                options.rules["required"] = true;
                if (options.message) {
                    options.messages["required"] = options.message;
                }
            }
        });
    </script>
}

Views/SignUp/ViewMessage.cshtml
@{
    ViewData["Title"] = "ViewMessage";
}

<h1>@ViewBag.ShowMessage</h1>